spring:
  application:
    name: apigateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: student-service
          uri: http://localhost:3000
          predicates:
            - Path=/api/students/**

server:
  port: 8080

jwt:
  secret: "dGhpc2lzYWpheWF0c2VjcmV0Zm9yaGp3dGhlcmVpc2Fsb25nc3RyaW5nZm9yaG1hY3NoYTI1NmtleQ"

app:
  name: "API Gateway"

logging:
  level:
    tn.universite.apigateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
